# --------------------------------------------------------------------------------------------------
# SPDX-License-Identifier: Apache-2.0
# --------------------------------------------------------------------------------------------------

add_subdirectory(cpp)

if(PROJECT_PARTS_PERF)
  add_subdirectory(perf)
endif()
